site_name: Candy
repo_url: https://github.com/krasninja/Candy
site_author: Ivan Kozhin

pages:
 - 'Introduction': 'index.md'
 - 'Calculations': 'calculations.md'
 - 'Common': 'common.md'
 - 'Domain': 'domain.md'
 - 'Extensions': 'extensions.md'
 - 'Helpers': 'helpers.md'
 - 'Validation': 'validation.md'
